In [1]:
import duckdb
import pandas as pd
from scripts import duckdb_functions as dbf

In [2]:
con = duckdb.connect("data/favorita.duckdb")
con.sql("SET memory_limit = '8GB'")            # оставить память Windows и Jupyter
con.sql("SET temp_directory = 'data/tmp'")     # куда сбрасывать при нехватке RAM
con.sql("SET preserve_insertion_order = false"); # меньше памяти при больших COPY

In [3]:
# con.sql("CALL start_ui()");

## Train

### Столбцы

In [ ]:
dbf.show_date_stats(con, "'data/landing/train.csv'", "date")
dbf.show_date_stats(con, "'data/landing/oil.csv'", "date")

                        date
column                  date
dtype                   DATE
total                   1218
not_null                1218
nulls                      0
duplicates                 0
min               2013-01-01
max               2017-08-31
span_days               1704
distinct_days           1218
continuous             False
missing_in_range         486
gaps                     243
first_gap_start   2013-01-05
first_gap_end     2013-01-06

In [5]:
dbf.show_num_stats(con, "'data/landing/stores.csv'", "store_nbr")

,column,dtype,total,not_null,nulls,duplicates,min,max,has_fraction,continuous,missing_in_range
store_nbr,store_nbr,BIGINT,54,54,0,0,1,54,False,True,0